### ISSUE TITLE
Replace django-enumfield

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-backend#180]
[django-enumfield](https://github.com/5monkeys/django-enumfield) doesn't seem to be under active development anymore.

https://github.com/hzdg/django-enumfields sounds similar, can it be used as replacement? (Has fewer stars on GitHub though)

**Comment by vinibiso** [comment]
I think I can takes this up if helps is still wanted.

**Comment by tiltec** [comment]
Thanks for the offer! A related topic came up some days ago when @nicksellen added group roles by writing plain strings into the database: https://github.com/yunity/foodsaving-backend/blob/master/foodsaving/groups/models.py#L61
We check them with an explicitly numerated `ChoiceField`: https://github.com/yunity/foodsaving-backend/blob/729efb028db30c5badd2f369c050046f475f9090/foodsaving/groups/serializers.py#L169

Rationale: it's nice if the database makes sense by itself, without the need to look up Python code.

So my idea was to remove all enumfields from our code and switch to plain text instead. Downside is only that it needs slightly more storage in the database, but I don't worry about that.

What do you think? Also ping @nicksellen

**Comment by vinibiso** [comment]
I see. Taking the example of Activity(History)

```
class ActivityTypus(enum.Enum):
    GROUP_CREATE = 0
    GROUP_MODIFY = 1
    GROUP_JOIN = 2
    GROUP_LEAVE = 3
    STORE_CREATE = 4
    STORE_MODIFY = 5
...
```

That works like the property [choices](https://docs.djangoproject.com/en/1.11/ref/models/fields/#choices) on a Django CharField right?

So the idea would be that enum out, replace it by using a straight CharField with choices?
I think that would work best if django-enumfield is not a option anymore.

**Comment by nicksellen** [comment]
Postgres supports enum types directly, and there is [an idea](https://code.djangoproject.com/ticket/24342) to include in django properly.

https://github.com/hzdg/django-enumfields seems like a reasonable approach to me, I figure it just uses chat/text fields in the db, but I did not look at it.

I don't think this is high priority, but if someone ones to implement would happily accept a PR :) - make sure to keep all existing values during migation of course...
