### ISSUE TITLE
Use django-configurations to manage settings.py

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-backend#230]
Config is getting more complex, so there's https://django-configurations.readthedocs.io/en/latest/ to help us.

**Comment by nicksellen** [comment]
Now I think is a good time to revive this, I actually needed a dev dependency that is used in the tests.

I tried an experiment so load config from `local_settings_d` directory, by adding this to `settings.py`:

```py
import os.path
import glob

local_settings_files = glob.glob(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'local_settings_d', '*.py'))
local_settings_files.sort()
for file in local_settings_files:
    module_name = '{}.local_settings_d.{}'.format(os.path.basename(os.path.dirname(os.path.abspath(__file__))), os.path.basename(file)[:-3])
    module = __import__(module_name, globals=globals(), locals=locals(), fromlist=('*'), level=0)
    for setting in dir(module):
        if setting == setting.upper():
            locals()[setting] = getattr(module, setting)
```

However, I think an environment-based approach is probably better.

The other main problem right now is the docker-compose setup mounts a `local_settings.py` file into the right place, but you IDE does not see it (as it's inside the docker container). Then when you edit `local_settings.py` it writes the file and that shadows the mounted one, and then it no longer has the magic docker settings, so tests don't run any more etc.

I'd like the docker-specific settings to have just the things that are needed differently. Perhaps having the docker setup use a different `DJANGO_SETTINGS_MODULE` would be better approach, to make it more explicit, maybe `docker_compose_settings.py`.

**Comment by tiltec** [comment]
I'd close this, it seems like we are doing fine juggling `local_settings.py` files...
