### ISSUE TITLE
Use task runner instead of cronjob

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-backend#242]
Rationale: have the recurring pickup generation inside git.

Celery seems to be good with Django. I worry a bit about the setup overhead.

http://docs.celeryproject.org/en/latest/userguide/

**Comment by yogesh-kamble** [comment]
We can use celery. can we discuss on this what task need to be added in celery in slack ?

**Comment by tiltec** [comment]
Sure, basically it's about two of our management commands that are currently run via cronjob. Works quite well for now, maybe we first focus on other issues/features. From the top of my head: user roles or mail notifications seem more important.

**Comment by vinibiso** [comment]
I have some experience with celery so far. I did the setup for another open source project.

I think it would be pretty easy since the project already uses redis as a broker.

ps.: can anyone join the slack?

**Comment by tiltec** [comment]
That would be a great addition!

Here's our current cronjob config (I'm too stupid to copy'n'paste from vim in ssh):
![image](https://user-images.githubusercontent.com/4410802/30100843-7908fc34-92ea-11e7-80bf-d511e7a13819.png)

It just runs the management commands _very_ often to pretend continuous changes.

> ps.: can anyone join the slack @tiltec?

Oh yes, please join us in Slack! http://slackin.yunity.org/ is the self-invite page, navigate to the "foodsaving-tool" channel afterwards. Looking forward to see you!

**Comment by nicksellen** [comment]
https://github.com/coleifer/huey looks quite nice too

**Comment by tiltec** [comment]
Done, we chose huey.
