### ISSUE TITLE
Feedback for finished pickups

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-backend#253]
For the frontend feature https://github.com/yunity/foodsaving-frontend/issues/159 we need a backend implementation.

I imagine two database fields per collector (user who did the pickup):

- comment: text (for future reference)
- weight: kilograms (for statistical purpose)

These information should be stored together with the pickup. Currently, the pickups (upcoming and finished) are all in one model, but I want to move the finished pickups to a new [`history` model](https://github.com/yunity/foodsaving-backend/blob/audit/foodsaving/history/models.py): 

An instance of PICKUP_DONE looks like this:

```json
  {  
    "id": "197",
    "date": "2017-02-22T14:59:22.442526Z",
    "typus": "PICKUP_DONE",
    "group": "5",
    "store": "22",
    "users": [
      "94",
      "90",
      "92",
      "100",
      "108"
    ],
    "payload": {
      "series": "22",
      "max_collectors": "10"
    }
  }
```

I propose to add the data to the `payload` field, which is a schema-less [Postgres JSONField](https://docs.djangoproject.com/en/1.10/ref/contrib/postgres/fields/#jsonfield).

As each collector can give one feedback, we could have a `user_feedback` object with each user id as key.

```json
...
"payload": {
  "series": "22",
  "max_collectors": "10",
  "user_feedback": {
    "94": {
      "comment": "There were many soft tomatos. Better bring some boxes next time.",
      "weight": "5"
    },
    "108": {
      "comment": "I can recommend this store. Nice and friendly!",
      "weight": "3"
    }
  }
}
```

What do you think about this data structure? Does it make sense to you?

Next steps are: design of API endpoints and serializer.

**Comment by Sliverriver** [comment]
is it just to have one feedback per user ? or also have multiple comments ?

**Comment by tiltec** [comment]
One feedback. What is the use case for multiple ones? I think if it needs to be updated, we can leave the field editable for some days after the feedback was given.

**Comment by tiltec** [comment]
@mddemarie Can you estimate when you will have time to work on this task?
Bruno raised focus on this feature here: https://github.com/yunity/foodsaving-frontend/issues/158

**Comment by mddemarie** [comment]
@tiltec I am sorry that I did not answer before. 
I tried to work on the issue today, but I have problems with my setup. I will try it again in the next days, but I am not sure if I will be successful soon. If you need it soon, I will need some help – or is it better for you if I give the issue back?
In some weeks I will have a lot more time (and help) – maybe you saw it in Slack?

**Comment by tiltec** [comment]
This is ready to work on, feel free to ask me any questions :)

**Comment by tiltec** [comment]
Given my latest insights in https://github.com/yunity/foodsaving-frontend/issues/159#issuecomment-318284870 and the recent Slack discussion, my data structure proposal from above seems like a bad choice:

- it requires modification of history events after they have been created (to add the feedback)
- it would make the history entry the original data source of the feedback. Whereas in all other cases, the history entry just stores metadata _about_ other models
- it requires complex database queries to fulfil the frontend needs: find out which users can give feedback, list all feedback per store, calculate statistics

Therefore, I propose: add a new `Feedback` model into the store's `models.py`. It should reference the user giving the feedback and the pick-up the feedback is about. This makes it easy to list the feedback per store and to calculate statistics.

```py
class Feedback(BaseModel):
  given_by = # reference to user model
  about = # reference to pickup date model
  weight = # positive number that will get interpreted as kilograms
  comment = # arbitrary text
```

The following API structure can be derived from it:

POST `/api/feedback/`: create a new feedback
GET `/api/feedback/?store=5`: list all feedback for store with ID 5

This should address (2) and (3) of the frontend requirements: https://github.com/yunity/foodsaving-frontend/issues/159#issuecomment-318284870

To make the reference to the pickup date model work, I will open another issue to make pickup date entries persistent (i.e. don't delete them when they are over).

**Comment by nicksellen** [comment]
I sat with @id-gue and @mddemarie - we went through all the initial conversations about what the feature was for (in slack, and the frontend/backend issues) to get a clearer understanding of why the feedback is useful.

We then explored some possible technical solutions of how to implement it, and discussed the pros/cons of each of them. Here are the notes I made whilst we chatted:

### Option 0 - current code

- when PickupDate is complete
- delete PickupDate (via command run once a minute)
- create PICKUP_DONE history entry

### Option 1 - CHANGE THE PAST!

- when PickupDate is complete
- delete PickupDate (via command run once a minute)
- create PICKUP_DONE history entry
- add feedback (comment and weight per user) in PICKUP_DONE history entry

comments:
- if user gives feedback before history entry is created, there is nowhere to store it
- involves editing history (just feels wrong! you cannot change the past)

### Option 2 - new Feedback model (Tilmann idea)

- never delete PickupDate entries (just filter for future or past ones depending on needs)
- probably still add PICKUP_DONE history entry when pickup is done
- new model Feedback (1 for each user/pickup combination) to collect comment and weight

comments:
- @mddemarie wonders: what is it good for? feels heavy
- @id-gue wonders: perhaps could be made into a more generic feedback/commentable model?
- simple because it is just creating normal models like the other ones (add your stuff in api.py/serializers.py/models.py etc...)

### Option 3 - store feedback on PickupDate model

- add weight and comment fields on PickupDate model
- use a JSONField to allow feedback for each user that did the pickup
- ... would also require not deleting old PickupDate items
- ... would probably also create PICKUP_DONE entry (to show in history tab...)
- very simliar to option 2, but using a JSONField instead of a seperate Feedback model

The current work has gone in this direction and can be seen here:
https://github.com/mddemarie/foodsaving-backend/commit/85e79e67703f3ba5f5cef7702239cfc0372afbcb?diff=split

comments:
- would be easier to implement for Ines/Marie as they already know mostly how to do it, option 2 feels like it would require a bunch more learning

### Option 4 - 24 hour feedback window

- keep PickupDate entry for 24 hours after it is complete
- allow feedback, and store in JSONField
- similar to option 1, then delete the PickupDate, and add a PICKUP_DONE history entry

comments:
- 24 hour window seems a good idea
- seems odd to implement time window in a technical way (storing in PickupDate table before, and history after)

**Comment by nicksellen** [comment]
would be grateful for your feedback @tiltec 

@id-gue was quite into option 2, and @mddemarie is warming up to it :)

**Comment by tiltec** [comment]
Thanks! Just briefly from my phone: Option 2 and 3 seem both worthwhile to me. They should be equally "heavy" - in the end, the data needs to be stored somewhere. I wouldn't worry about that.

The reasons why I prefer option 2:
- consistency: same structure as all other models
- it seems slightly easier to me to work with database fields than with nested json structures
- "giving feedback" would be a completely separate action from "modifying a pick-up date", also data-wise
- a new separate endpoint is more extensible, e.g. if we want to give user the possibility to edit the feedback (feature request exists)

In the end, both should be fine and I will support both options as much as I can. But I know option 2 better.

**Comment by id-gue** [comment]
@tiltec so we will work on option 2! :)

I think it might be the best to remove our code changes and start from scratch, right? The only thing we could commit now is the new permission class IsPast, right? 

Everything else should be refactored.

**Comment by tiltec** [comment]
## create a new feedback

`POST /api/feedback/`

with data

```json
{
    "about": 33,
    "weight": 2,
    "comment": "string"
}
```

## get a list of all feedbacks:

`GET /api/feedback/`

should return

```json
[
  {
    "id": 1,
    "given_by": 33,
    "about": 33,
    "weight": 2,
    "comment": "string"
  },
  {
    "id": 2,
    "given_by": 34,
    "about": 33,
    "weight": 2,
    "comment": "string"
  }
]
```

and so on.

## Edge case to consider

What happens when a user is trying to

- give a feedback for a pickup that he didn't do (= is not part of the `collectors`)?
- give a feedback on a pickup that is not done yet (`date` is not in the past)?
- get a feedback for a pickup in a store in a group when he is not a member of the group? (should not be found)

There's surely more that I didn't think of yet :) Makes sense to create test cases and then improve the code, as I mentioned in our call.

**Comment by id-gue** [comment]
https://github.com/yunity/foodsaving-backend/pull/337

**Comment by mddemarie** [comment]
@tiltec About who GETs the Feedback (just to be sure):

non-user gets 400
user gets 400
group member gets 200

Right?

(And wouldn't the Feedback be interesting for users-but-not-group-members, too?)

**Comment by tiltec** [comment]
Yes, that seems correct (user means non-member). Although it should be 404 ("Not found") instead of 400 ("Bad request") in case of GET.

> (And wouldn't the Feedback be interesting for users-but-not-group-members, too?)

I don't think so. I think that the groups are generally private/closed and don't want to have internals of their pick-ups leaking to non-members or non-users.

**Comment by id-gue** [comment]
Ok, great. Thank you!

**Comment by tiltec** [comment]
I continued working on the beta-frontend for giving feedback and discovered that I can submit multiple feedback for the same pickup. Maybe worth a fix :)

**Comment by id-gue** [comment]
Hi @tiltec so there are 3 things we should change:

1. add filters (by group, store and pickup-date)
2. limit multiple feedback for the same pickup per collector
3. make sure that weight=null AND comment=null fails

Optional:

- refactoring `about`
- editing given feedback
- at the moment every collector can give a weight estimation - do we want an average weight? If yes: does that require additional backend functionality?

**Comment by tiltec** [comment]
Yes, sounds good!

> editing given feedback

That would make users happy, I think.
Perhaps we should limit the overall period in which feedback can be given and edited to, say, 1 month after it has been done?

> at the moment every collector can give a weight estimation - do we want an average weight? If yes: does that require additional backend functionality?

This would be a nice follow-up task: creating statistics. Maybe we schedule a call before you start working on that? 
Related issues: https://github.com/yunity/foodsaving-frontend/issues/355 https://github.com/yunity/foodsaving-frontend/issues/159

**Comment by tiltec** [comment]
Currently, `weight` is a `PositiveIntegerField`, but I think we should also allow fractions of kilograms. Maybe the `FloatField` is a better choice? It would need checking for values smaller than zero though.

**Comment by mddemarie** [comment]
Thank you for your reply.
We make a plan for adding more functionality to Feedback tomorrow.

**Comment by tiltec** [comment]
Hey, just saw it in your dailylog and have feedback regarding it:

> 1. 
> - Make sure that weight=null AND comment=null fails
> - Change ‘weight’ field to FloatField
> - Add PATCH
> - Refacture the field `about`
> 2.
> - Add filters
> - Limit multiple feedback for the same pickup per collector
> - Limit the overall period in which feedback can be given

As filters are pretty important for the frontend, I would pull them into (1).
I think "Limit multiple feedback for the same pickup per collector" is also quite important to avoid inconsistencies.

Adding PATCH needs a bit more fiddling (e.g. make sure that the `about` field is not changed), so I would move it to (2).

Also, I'd suggest to make small Pull Request for each change, this way we can integrate them faster.

So my suggestion would be to reorder them by type of change and priorities. No new task added :)

1. Fixes
- Limit multiple feedback for the same pickup per collector
- Make sure that weight=null AND comment=null fails
- Change ‘weight’ field to FloatField

2. Necessary functionality
- Add filters

3. Niceties
- Add PATCH
- Refactor the field `about`
- Limit the overall period in which feedback can be given

4. New feature
- Statistics

Of course, if you are more motivated to work on one of the "further ahead" tasks, that's totally fine with me too!

**Comment by tiltec** [comment]
This seems to be mostly done, we should now implement it in the frontend and get user feedback!
