### ISSUE TITLE
Better support for dev dependencies

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-backend#355]
I added a dev library for use in testing, then found the workflow for managing dev dependencies a bit lacking.

Currently for dependencies I run `pip-compile && pip-sync`, but this would uninstall things from `dependencies-dev.txt`.

https://github.com/jazzband/pip-tools/issues/398 has some ideas. I'm thinking to include a `dependencies-dev.in`.

Then updating everything is done with:
```
pip-compile && pip-compile requirements-dev.in && pip-sync requirements*.txt
```

Which could go into an `update-deps.py` command (so it's cross platform).

**Comment by tiltec** [comment]
`requirements-dev.in` and `requirements-dev.txt` sounds good.

Ideally we would have two commands: compile+sync (could be called `update-deps.py`) and sync only. The latter would be needed for dev setup, CI and deployment.
