### ISSUE TITLE
Rethink custom signals vs builtin ORM ones

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-backend#361]
The topic came up here https://github.com/yunity/foodsaving-backend/pull/357#discussion_r136218027

My feeling at the moment is that the custom signals are leading to higher coupling. At the moment it feels like I need to know what the signal is going to be used for before I choose to sent it (or not) - I don't have a clear concept of the custom signals.

The advantage of the builtin ones are:
* no choice about when to send - simple concept
* don't have to add signal sending all over the codebase
* no chance to miss a case
* permits you to use the normal ORM without having to keep in mind the custom signals

Disadvantages are:
* intentions _sounds_ like clear: _post_save on GroupMembership and check for created==True_ vs _post_group_join_
* lose precise control over when they are sent
* cannot add custom arguments for the signal handlers to use

I would see three ways forward that could make sense:
1. create a clearer concept of the custom signals (what they mean, when they should be sent, how they differ from ORM ones)
2. send custom signals from ORM signal handlers (best of both?)
3. just use ORM signals

I like 2, but see some potential for the 1. 3 is like a simple default for me.

**Comment by tiltec** [comment]
The use of signals is inconsistent indeed. This is mostly about the history model. Some things to consider:

- How to control which data are recorded in the history? Currently we only record changed values, they get sent via signals.
- Some signals don't exist in the ORM, e.g. we don't delete stores but only erase data their data. Still, a history event should be recorded for it.

> 2. send custom signals from ORM signal handlers 

How would this look?

**Comment by nicksellen** [comment]
> This is mostly about the history model

Yes, this is a good point. That is the underlying thing here.

Maybe it's better to just write into the history explicitly with a helper function.

_something somewhere_ needs to express the logic of when to write what into the history, and it will probably always include some metadata (that may not be stored elsewhere in the database).

I think the current custom signals are _really_ just _write entry into history_ triggers.

**Comment by tiltec** [comment]
So we have two solutions:

- have one signal *history_push* and the semantics (typus, payload) are described via signal payload
- get rid of signals and use tight coupling with a helper function

The latter seems to be my preferred solution. Don't use the cognitive overhead of signals when it's not needed.

**Comment by nicksellen** [comment]
Yes, I would go with the latter solution. A signal should be about what has happened (that something else might want to do something about), not what you intend to happen (that is achieved with a function/method call).

I don't think it is tighter coupling, as we already have the signals for that specific purpose, just they are not explicit about that. So we are making things explicit and changing the mechanism.
