### ISSUE TITLE
Show visualization of database models

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-backend#365]
This one could be helpful: https://django-extensions.readthedocs.io/en/latest/graph_models.html

**Comment by nicksellen** [comment]
Here is what it looks like, works out the box! We already have django-extensions in the app, so I just did:

```
pip install pygraphviz
./manage.py graph_models -a -g -o fstooldb.png
```

![fstooldb](https://user-images.githubusercontent.com/31616/29937532-cadae142-8e7d-11e7-985e-b7f3174416ab.png)

ping @Sliverriver

**Comment by nicksellen** [comment]
Ok, a slightly easier to read one, skipping some less important models, created with:

```
./manage.py graph_models -g -X AbstractBaseUser,LocationModel,BaseModel,NicelyFormattedModel -o ~/Downloads/fstooldb.png conversations users groups stores subscriptions
```

![fstooldb](https://user-images.githubusercontent.com/31616/29941736-7018ec8c-8e8b-11e7-943c-09ff1448b7a4.png)

**Comment by nicksellen** [comment]
So, the useful thing would be to run it during build or deployment, and make it available at a public URL somewhere.

**Comment by tiltec** [comment]
If we keep the file in git, it could be properly embedded into README (or some other file). Maybe we can extend the django makemigrations command?
