### ISSUE TITLE
Refactor: Split up store app

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-backend#368]
Currently the store app is the most complex Django app in our project. It contains `store`, `pickupDate`, `pickupDateSeries` and `Feedback` models, serializers, views and related logic.

It seems easily possible to split it up into separate Django apps to have better overview and less unrelated code when modifying files.
We could make it so that Django apps largely mirror API endpoint names.

**Comment by nicksellen** [comment]
Will be especially helpful if we make pickup dates abstracted into tasks.

**Comment by tiltec** [comment]
Correct @vinibiso, plus pickupDateSeries could also be a separate app. They are somehow coupled to the pickupDate model, but not very tightly.

Currently, there are two devs working on the Feedback model #253, so it would be good to wait until their changes are merged.

**Comment by nicksellen** [comment]
I like the idea to separate into apps, but `pickupDateSeries` in it's own app is taking the concept too far IMO. The separation between app and model would become very fine. I'd probably just split `pickup*` and `feedback` models into a pickups app.

**Comment by tiltec** [comment]
They all have dependencies to each other. Let me highlight some.

- `PickupDate` is dependent on  `Store`. The `series` ForeignKey is optional (only when it's part of a series).
- `PickupDateSeries` needs values from the `Store` model (`weeks_in_advance`) to generate `PickupDate` entries.
- `Feedback` depends on `PickupDate`.

So whatever we do, it means breaking things apart that are somehow coupled. Maybe it's best for now to do what Nick said, creating a new `pickups` app for PickupDate, PickupDateSeries and Feedback.

Maybe it makes sense to move the `weeks_in_advance` setting away from the store. It controls how many weeks in advance a series will create pickupDates (analog to foodsharing.de behavior). Maybe there's a better solution, e.g. controlling this setting per series and not per store.
