### ISSUE TITLE
Add optional agreement for groups

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-backend#385]
This is the backend implementation of https://github.com/yunity/foodsaving-frontend/issues/324#issuecomment-312685256, this is the proposal from a discussion between me, @tiltec, and @djahnie:

> 0. The legal agreement should be optional and per-group, decided by group admins
> 1. We need some people (group admins) in the group who are able to edit the legal agreement -> #356 
> 2. If the legal agreements gets changed, all members have to accept again (simpler implementation)
> 3.1 If users are already in the group and have not accepted the latest agreement, they should be showed a dialog and be prompted to agree on it.
> 3.2 If users join a group, joining and accepting should be done in one step
> 
> Probably we could record the date when the users agreed, so we could later compare it to the change time of the agreement.

I don't think any of the subsequent discussion changes that idea.

For implementation, my initial idea was to:
* add a new group role (using our new roles system) called `GROUP_AGREEMENT_MANAGER` (the existing one being `GROUP_MEMBERSHIP_MANAGER`)
* add a `groups.Agreement` model which has `title`, and `content` text fields
* add a one2one relationship from group -> agreements (denoting the active agreement)
* add a foreign from agreements -> group (denoting which group an agreement is related to)
* add an agreed_to foreign key to agreements on group membership (recording the agreement a given user has agreed to)

Rationales:
* minor changes to the agreement (e.g. typo, italic change, new line added) does not need to get everyone to re-agree (what is minor is up to the group/law to decide)
* we record explicitly which agreement a user agreed to instead of implicitly by date
* we keep the history of agreements as is useful (could prune them where nothing refers to them anymore, but seems potentially useful to keep any agreement that is refered to in an agreed_to field, presumably the old agreement is still fine for letting them browse the site, but they would need to accept the new agreement to do certain other things)

**Comment by tiltec** [comment]
Seems to be a good model. I thought about using something like https://github.com/etianen/django-reversion from model versions & rollback, but it doesn't fit this purpose.

How would the transition between "group without agreement" and "group with agreement" look like? And the reverse?

**adding agreement**

- the user with `GROUP_MEMBERSHIP_MANAGER` appoints someone as `GROUP_AGREEMENT_MANAGER`
- `GROUP_AGREEMENT_MANAGER` pushes an agreement and set it as active (one2one)
- all users have to agree before they can do any action inside the group

**removing an agreement***

- `GROUP_AGREEMENT_MANAGER` removes the active agreement

**switching agreements (major change)**

- `GROUP_AGREEMENT_MANAGER` writes a new agreement and changes the active agreement

**Comment by nicksellen** [comment]
So #417 implements the most basic features we can merge, still not addressed are:

- [ ] ensure the membership manager can assign agreement managers
- [ ] probably initialize an agreement manager so there is an initial one
- [ ] limiting certain actions depending on agreement status (e.g. users should not be able to do pickups unless they have agreed)
- [ ] add information on who has agreed to the API (see https://github.com/yunity/karrot-backend/pull/417#discussion_r147576846)
- [ ] implement the frontend

Two things I think I don't need to implement (at least right now) are:
- deleting agreements
- unagreeing (gets more complicated as it might depend on what is inside the agreement content, so might need to be set whether it can be unagreed or not, per agreement, probably does not matter for now)

**Comment by tiltec** [comment]
Moved to https://github.com/yunity/karrot-frontend/issues/324#issuecomment-369940704
