### ISSUE TITLE
Make (serializer) validation safe for concurrent requests

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-backend#409]
(Almost) all our serializer validations behave incorrect on concurrent requests, which leads to server errors or corrupted data.

For example joining a pick-up as collector: if there is one slot free and two users join at the same time, they might both pass the serializer validation. The database doesn't check for `max_collectors`, hence both will be added as collectors.

The reason for this behaviour is that both requests run in separate threads (EDIT: or processes even). What I usually imagine when writing backend code is the following:

```
_Request 1:_ start1 - read1 - validate1 - write1 - respond1
_Request 2:_ ------------------------------------------- start1 - read2 - validate2 - (fail validation!)
```

Request 2 fails because `read2` happens after `write1`.

Here's what supposedly happens when two requests arrive in short succession:

```
_Request 1:_ start1 - read1 ----- validate1 ---- write1 - respond1
_Request 2:_ --------- start2 - read2 ---- validate2 ---- write2 - respond2
```

Notice how `read2` and `validate2` happen before `write1`? Of course both requests will pass validation!

I experienced similar problems if the same user fires two request to join a pick-up in short succession. Here however, the database checks the `unique` constraint when writing and hence Django responds with HTTP500.

One fits-all solution is to wrap `create` and `update` ViewSet methods into Djangos [`@transaction.atomic`](https://docs.djangoproject.com/en/1.11/topics/db/transactions/#django.db.transaction.atomic) decorator. This has a slight performance drawback, but should prevent all incorrect behaviour.

There are two caveats mentions in the [docs](https://docs.djangoproject.com/en/1.11/topics/db/transactions/#django.db.transaction.atomic): "Don't catch database exceptions inside atomic()" and "Revert model state manually when rolling back a transaction". We have to see how they apply.

**Comment by tiltec** [comment]
Another solution would be to express all constraints at database-level and handle `IntegrityErrors` properly. But since this has some problems, it could only be used in addition to serializer validation and viewset permission handling.

More details:

### Django doesn't support custom constraints nicely (yet)

There is an active but long-running PR to add DB constraints via model `Meta`: https://github.com/django/django/pull/7615
It might arrive in Django 2.0, to be expected in December 2017.
Here's an example how to use it: https://github.com/Ian-Foote/django/blob/f416afe15933432488ee2c61ccea2dcef6ffa543/docs/ref/models/options.txt#L434

I would prefer this much over plain `RunSQL` migrations, like described there: https://www.fusionbox.com/blog/detail/custom-database-constraints-in-django/594/

### DRF doesn't handle `IntegrityErrors` nicely

`IntegrityErrors` are only catched at a very late stage in Django, causing it to return HTTP500. To return meaningful messages, we would need to catch and convert them to HTTP400 with a nice structured error message that is understandable to the frontend. As you will see, this is not easy:

An example `IntegrityError`:

```
duplicate key value violates unique constraint "users_user_email_key"
DETAIL:  Key (email)=(test@example.com) already exists.
```

It only returns a string (probably database-specific). That makes generating structured error messages hard.

---

Recap:

Creating and updating models in DRF works like this:

1. Request comes in
2. Run ViewSet request methods (`create`, `update`); check permissions; if `update`, model is fetched from `queryset`
    -> if permission check failed, return HTT403
    -> if model is not found, return HTTP404
3. Serializer validates request data against static constraints ("is field required?") and existing data ("is user in group?")
    -> if validation fails, raise `ValidationError` and return HTTP400
4. Serializer calls `save()` on model instance
    -> if save fails, raise `IntegrityError` and return HTTP500

### Takeaway

There is probably no (nice) way around atomic transactions for now. They should work just fine.

When Django gets custom constraints in future, we could drop atomic transactions for improved speed, as long as we add appropriate constraints. This will also increase robustness against people (or other applications) fiddling with the database directly. We should have both: 

- Database constraints to ensure integrity; don't catch them (return HTTP500)
- Serializer validation as before to have nice errors for 99.999% of all request

**Comment by tiltec** [comment]
After some tests and experiments, I found out that using `transaction.atomic` is only part of the solution. While it wraps everything inside a transaction, the [default isolation level](https://docs.djangoproject.com/en/1.11/ref/databases/#isolation-level) is "read committed", which [allows for non-repeatable reads](https://www.postgresql.org/docs/current/static/transaction-iso.html).

Using a higher isolation level should solve the problem, but people report worse performance. In my experiment, only "serializable" prevented the race condition, "repeatable read" didn't help. I only applied the isolation [to one endpoint](https://stackoverflow.com/questions/30955733/in-django-how-to-achieve-repeatable-reads-for-a-transaction), not for the whole application.

Djangos [`select_for_update`](https://docs.djangoproject.com/en/1.11/ref/models/querysets/#select-for-update) Queryset method could also help in some cases, but I'm not sure if it helps in the pickup-join case: a row in the many-to-many table gets added, how should a row-lock help? Also, explicit locking is cumbersome and can introduce deadlocks.

There's also the [approach to do _optimistic writes_](https://invalidpatent.wordpress.com/2016/08/03/two-approaches-to-concurrent-write-safety-in-django/) and abort the transaction if a post-condition doesn't fulfil some expectations. That seems generally a high-performance solution, but maybe hard to get right.

The linked page in the last paragraph has also some other options to offer, e.g. doing `filter` + `update` while checking a `modified_at` value. If not successful, throw an error to roll back the transaction. I wonder if this can also be applied to more complex cases, e.g. many-to-many changes. Furthermore, update doesn't trigger signals, that would need to be done manually.

**Comment by nicksellen** [comment]
I think getting it to lock the pickup row via a select for update call will work here. It's the pickup that is the contended/shared item, not the many-to-many table entry.

From https://www.postgresql.org/docs/current/static/transaction-iso.html

> UPDATE, DELETE, SELECT FOR UPDATE, and SELECT FOR SHARE commands behave the same as SELECT in terms of searching for target rows: they will only find target rows that were committed as of the command start time. However, such a target row might have already been updated (or deleted or locked) by another concurrent transaction by the time it is found. In this case, the would-be updater will wait for the first updating transaction to commit or roll back (if it is still in progress)

So, I _think_ "read comitted" + "select <pickup> for update" should work.

For implementing in django/drf then a `transaction.atomic` followed by a `select_for_update` call (which could be wrapped in a custom decorator) would work...

**Comment by tiltec** [comment]
I'll try it out!

**Comment by tiltec** [comment]
My current approach with `select_for_update` locking went quite well (have a look in #411), but there are database deadlocks in my latest test case (somebody deletes a series and somebody else joins a pickup of this series at the same time).

I think this needs more work or a different approach. Given that concurrency bugs have almost never occurred in production (as far as I know), it would be reasonable to let this sleep for a while and have a look again when the app is becoming more heavily used.

**Comment by tiltec** [comment]
Not important right now, I'll keep the PR around though.

**Comment by brnsolikyl** [comment]
Just got reported a possible case for this: two people signed up at the same time for an activity that had only one slot, and now it shows that they are both signed up for it. When checking the settings for this activity, it actually shows 1 slot.

group/10/place/510/, the activity on the 09/11 if you want to check the db. Users 234 and 1942

**Comment by nicksellen** [comment]
> Django doesn't support custom constraints nicely (yet)

Seems like it does now! Since 3.0 --> https://docs.djangoproject.com/en/3.1/ref/contrib/postgres/constraints/

I didn't look in detail, so not sure if it can cover that case.
