### ISSUE TITLE
Request additional PyCharm licenses

### ISSUE THREAD

**Issue by mr-kojo** [yunity/karrot-backend#426]
...for new developers

**Comment by tiltec** [comment]
We have 4 JetBrains all-product licenses, I think 3 of them are in use by me, @nicksellen and @NerdyProjects. So we should have one license left. I'm not sure how to give one to you though.

Generally it could make sense to ask for more licenses again, we had 8 during yunity times.

**Comment by tiltec** [comment]
This issue makes also sense in the central (frontend) repo, as IntelliJ is quite a good frontend editor as well. @nicksellen uses it a lot for front- and backend.
IntelliJ with the python plugin is equal to PyCharm.

**Comment by mr-kojo** [comment]
Moved to karrot-frontend repo
