### ISSUE TITLE
Most cryptic error message I've seen in here so far

### ISSUE THREAD

**Issue by djahnie** [yunity/karrot-backend#438]
It's when trying to invite a user, who has already (successfully..?) been invited.

![image](https://user-images.githubusercontent.com/17573771/32912961-189349d6-cb11-11e7-89b0-21412ce121af.png)

It took me 10 seconds to get that the mail was already used. I wanted to change it myself, but I don't have the backend.

My proposal: "An invitation has already been sent to this email adress." or "An invitation has already been accepted for this email adress.". Whatever is closer to the truth...

**Comment by NerdyProjects** [comment]
@tiltec says this is okay for now. :D If you just need 10 seconds, where is the problem?

**Comment by djahnie** [comment]
Hm well, I could imagine that there are people, who wouldn't get it at all... I'm just trying to help, there's always room for imrpovements... 😋

**Comment by tiltec** [comment]
It's true that the backend error message is a bit cryptic, but it's the default from Django REST Framework and I don't know where to change it. Ideally it should never show to the user anyway. The invite form is apparently missing proper front-end validation.

This bit should have prevented it:
https://github.com/yunity/karrot-frontend/blob/9b82efd73e4d7b3397ea615198c11d202cbd6f87/src/components/Group/InvitationsForm.vue#L55-L58

Could you file a frontend issue?

**Comment by djahnie** [comment]
Sure! 😊 
Thanks for the appreciation, @tiltec ! 😘
