### ISSUE TITLE
Swagger links broken

### ISSUE THREAD

**Issue by mr-kojo** [yunity/karrot-backend#460]
For some reason, Swagger somehow tries to escape slashes in URLs.
E.g., it prints `http://localhost:8000/api\/auth\/logout\/` instead of `http://localhost:8000/api/auth/logout/`.

Maybe this is related to #459?

**Comment by tiltec** [comment]
Thanks for reporting, does this break swagger?

There's a related bug that only shows on deployment and breaks the browsable API: https://github.com/yunity/karrot-frontend/issues/725
I spent some hours on it, but couldn't find out the root cause.

**Comment by mr-kojo** [comment]
> Thanks for reporting, does this break swagger?

Swagger still works, except that using the "Try it out!" button always raises a `404`.

**Comment by mr-kojo** [comment]
> Thanks for reporting, does this break swagger?
Swagger still works, except that the "Try it out" button always raises a 404.

I observe the issue both on my local server as well as on [dev.karrot.world/docs/](dev.karrot.world/docs/) but not on [karrot.world/docs/](karrot.world/docs/). So it seems to be the result of a recent commit.

**Comment by tiltec** [comment]
Ah, found it! It's an upstream problem: https://github.com/marcgibbons/django-rest-swagger/issues/718

**Comment by tiltec** [comment]
Should be fixed in DRF 3.7.4 that arrives soon.
