### ISSUE TITLE
New Feature - Social Network Integration

### ISSUE THREAD

**Issue by riyasinha** [yunity/karrot-backend#499]
We could integrate Facebook and Google SignIn with the user profile. This feature could be extended to facebook groups and google circles. @snehalgupta and I would love to work on this!

**Comment by tiltec** [comment]
Is this related to https://github.com/yunity/karrot-frontend/issues/154 ?
If yes, please read the discussion there. In short: it would be a nice feature, but it might need some fiddling around to implement it in a good way. I'd be happy to guide you through the process if you have enough time at your hand (I expect several weeks).

**Comment by tiltec** [comment]
Or do you think more of a feature where people can connect their account on karrot.world with their facebook and google accounts?

(Please open issues in the frontend repository, I'll disable the backend issue tracker very soon. See #488

**Comment by riyasinha** [comment]
We are thinking more along the lines of connecting facebook and google accounts to karrot.world.
We would love your guidance through this.
I will open this issue again on the front end repository. 
Sorry for ignorance.

**Comment by tiltec** [comment]
Okay, then let's continue in the frontend repo :)
