### ISSUE TITLE
Investigate auto formatting python tools

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-backend#510]
https://github.com/hhatto/autopep8 will format to pep8 standard minimally, we have it dev dependencies but don't have a simple to run it across all files.

https://github.com/google/yapf goes a lot further and will format it to look pretty and follow a codestyle, you can put something like:

```
[style]
based_on_style = pep8
spaces_before_comment = 4
split_before_logical_operator = true
```

in  `.style.yapf` and then it will format it!

**Comment by nicksellen** [comment]
I added an autoformat command to the docker setup, using autopep8 and autoflake [1] (which handles removing unused imports).

https://github.com/yunity/karrot-docker/blob/master/scripts/autoformat

[1] https://github.com/myint/autoflake

**Comment by tiltec** [comment]
I guess we'll switch to yapf during a quiet time #524
