### ISSUE TITLE
DevOps: Grafana login broken

### ISSUE THREAD

**Issue by mr-kojo** [yunity/karrot-backend#514]
The GitHub OAuth somehow doesn't work...

![unbenannt](https://user-images.githubusercontent.com/16634824/36910556-63476ef2-1e41-11e8-80ca-22ed5d40f8b2.PNG)

**Comment by tiltec** [comment]
Is this resolved? I can see mr-kojo in the user list, with last activity 4 days ago.

**Comment by mr-kojo** [comment]
Yes, Nick fixed it
