### ISSUE TITLE
Joining/leaving a pickup unsubscribes conversation-only subscribers

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-backend#860]
It's possible to join the conversation for any pickup, regardless of whether you are a collector or not. But when anyone else joins, or leaves, the logic to sync the conversation participants to only the pickup collectors is run, so anybody that joined the conversation but was not a collector, will be removed from the conversation.

You can recreate it like this:
- login with two seperate users and view the pickup list, e.g. on https://dev.karrot.world/#/group/6/pickups
- with one user, click on a pickup and write something in the pickup chat, they become subscribed
- with the other user, join that same pickup
- notice for the first user, they are unsubscribed from the conversation

I didn't think so much about the fix, as I just noticed it randomly reading the code, but maybe we need to stop using `sync_users` for this case - and switch to explicitly add/removing members on join/leave pickup. Alternatively, maybe the conversation only people are distinguishable in some other way they can not be removed? (but I don't think that way would make so much sense).

https://github.com/yunity/karrot-backend/blob/cb8a4dd52f69bcb399ab8bf8991a202c17e5f3e0/karrot/pickups/receivers.py#L49-L55

**Comment by tiltec** [comment]
Explicit add/remove seems the way to go. I wonder if there are other usages of sync_users that cause that effect?
